name: Database CI

on:
  push:
    paths:
      - 'database/**'
      - 'package.json'
  pull_request:
    paths:
      - 'database/**'
      - 'package.json'

jobs:
  test-database:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build and test database
      run: npm run db:update
      
    - name: Verify database integrity
      run: npm run db:verify
      
    - name: Upload database artifact
      uses: actions/upload-artifact@v3
      with:
        name: plant-varieties-database
        path: database/plant_varieties.db
        retention-days: 7