name: Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Count warnings
      run: |
        WARNING_COUNT=$(npm run lint 2>&1 | grep -c "warning" || echo "0")
        echo "ESLint warnings: $WARNING_COUNT"
        if [ $WARNING_COUNT -gt 25 ]; then
          echo "::error::Too many ESLint warnings ($WARNING_COUNT). Threshold is 25."
          exit 1
        elif [ $WARNING_COUNT -gt 10 ]; then
          echo "::warning::ESLint warnings approaching threshold ($WARNING_COUNT/25)"
        fi
    
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
    
    - name: Check test coverage
      run: |
        COVERAGE=$(npm test -- --coverage --watchAll=false --silent | grep "All files" | awk '{print $10}' | sed 's/%//')
        echo "Test coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 50" | bc -l) )); then
          echo "::warning::Test coverage below 50% ($COVERAGE%)"
        fi